### ISSUE TITLE
Couldn't write seqLogo(pwm) as png file

### ISSUE THREAD

**Issue by Evenlyeven** [ivanek/seqLogo#3] opened 2023-03-03 20:39 UTC
Thanks for developing this tool for PWM visualization!

seqLogo(pwm) showed a nice sequence logo plot. However, when I tried to save it as a png file using png(), it didn't work. I wonder if you know why. Thanks!

My script 1:

`png(filename = paste0(plot_root, "15_seqlogo.png", width = 800, height = 500))`
`seqLogo(pwm)`
`dev.off()`

My script 2:

`png(filename = paste0(plot_root, "15_seqlogo.png", width = 800, height = 500))`
`p <- seqLogo(pwm)`
`plot(p)`
`dev.off()`

In script 2, p is NULL after `p <- seqLogo(pwm)`

Thank you in advance!

**Comment by ivanek** [comment] 2023-03-08 12:59
Dear @Evenlyeven,

It is hard for me to debug as you did not provide a completely reproducible code. I do not know what is the content of `pwm` variable. 

Also in your code the closing brackets are not at the right position. 

Below is the code which works for me to generate a PNG image of a sequence logo.

```
library(seqLogo)

mFile <- system.file("extdata/pwm1", package = "seqLogo")
m <- read.table(mFile)
p <- makePWM(m)

plot_root<- "./"

png(filename = paste0(plot_root, "15_seqlogo.png"), width = 800, height = 500)
seqLogo(p)
dev.off()
```

![15_seqlogo](https://user-images.githubusercontent.com/646540/223719163-72fcf655-d57a-4f3a-adde-65afa8c2c6ba.png)

**Closed as completed by ivanek** 2023-03-08 12:59 UTC
Labels: invalid

**Comment by Evenlyeven** [comment] 2023-06-13 17:55
> 

Thanks for your reply! It was my scripts that was wrong as you mentioned, it took me a while, thanks for pointing that out. And lastly, thanks for developing this cool and useful package!
